baseurl = "sapuglha.com"
title = "I, code"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Tiago Silva"
    description = "Tighten droids' nuts and bolts"
    keywords = "blog,developer,personal"
    info = "Tighten droids' nuts and bolts"

    hideCredits = false
    hideCopyright = false

    # Custom CSS
	custom_css = []

[[params.social]]
    name = "Github"
	icon = "fa fa-github fa-2x"
    weight = 1
    url = "https://github.com/sapuglha/"
[[params.social]]
    name = "Mastodon"
	icon = "fa fa-mastodon fa-2x"
    weight = 2
    url = "https://androiddev.social/@sapuglha"
	rel = "me"
[[params.social]]
    name = "Twitter"
	icon = "fa fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/sapuglha/"
[[params.social]]
    name = "LinkedIn"
	icon = "fa fa-linkedin fa-2x"
    weight = 4
    url = "https://www.linkedin.com/in/TiagoSantannaSilva/"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/post/"

[[menu.main]]
    name = "Talks"
    weight = 2
    url  = "/talk/"

[[menu.main]]
    name = "About"
    weight = 3
    url = "/about/"
